### ISSUE TITLE
-debug doesn't work with specs2

### ISSUE THREAD

**Issue by ianpojman** [Tapad/sbt-docker-compose#102]
The specs2 command line doesn't like the -J (which perhaps scalatest's runner is using). I hacked this locally by handling Specs2 differently. If you have a preferred solution I can maybe find time to make a proper PR.

```
 protected def runInContainer(testDesc: String, run: ExecuteInput.Invoke)(implicit state: State, args: Seq[String], instance: Option[RunningInstanceInfo]): State = {

    val extraTestParams = runTestExecutionExtraConfigTask(state).map { case (k, v) => s"-D$k=$v" }

    binPackageTests

    // Looks for the <-debug:port> argument and will suspend test case execution until a debugger is attached
    val debugSettings: String = getArgValue(testDebugPortArg, args) match {
      case Some(port) =>
        run match {
          // --- quick fix for debugging Specs2 ---
          case ExecuteInput.Specs2 =>
            s"-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=$port"
          case _ =>
            s"-J-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=$port"
        }
      case None => ""
    }
```

**Comment by kurtkopchik** [comment]
Hi @ianpojman - Thanks for reporting the issue and identifying the fix!

It turns out that this was a regression when the command to launch tests was switched to use the `java` process instead of `scala`. The fix involved removing the `-J` from all `ExecuteInput` types.

I've released an updated version with this fix. Please let me know if it works for you.

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.31")`

**Comment by ianpojman** [comment]
Sweet. Everything else is working great so far. Thanks!
