### ISSUE TITLE
variablesForSubstitution would be more useful as a Task

### ISSUE THREAD

**Issue by jmcclell** [Tapad/sbt-docker-compose#30]
Currently I'm trying to keep certain configuration in one spot and to load it I need the fullClasspath which, in sbt, is a Task. This means I can't use my config in the substitution variables for my compose files which means I have to repeat things and .. well.. that sucks. :(

Thoughts?

**Comment by kurtkopchik** [comment]
Hi @jmcclell. Thanks for the feedback and for checking out the plug-in.

I'm not 100% sure I understand your exact use case but would you be able to create your own Task that reads the proper configuration from the shared location into a `Map` and then populates `variablesForSubstitution` with that data. Something in build.sbt like:

```
TaskKey[Unit]("getConfigData") :=  {
  val configDataPath = (fullClasspath in Compile).value
  println(s"Get config data from location '$configDataPath' and create Map to assign to variablesForSubstitution")
  variablesForSubstitution := Map(<from shared config data location>)
}
```

**Comment by kurtkopchik** [comment]
Hi again @jmcclell 

I released a `1.0.14-SNAPSHOT` version of the plug-in that contains a new `variablesForSubstitutionTask` so that you can now easily do things like get the `fullClasspath` and dynamically build your variable substitution mappings.

You can get the plug-in here:
```
resolvers += "Sonatype Snaopshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.14-SNAPSHOT")
```

From build.sbt you can use the new task as follows:
```
variablesForSubstitutionTask := {
  val configDataPath = (fullClasspath in Compile).value
  println(s"Get config data from $configDataPath and create Map to return")
  Map("SOURCE_PORT" -> "5555")
}
```

The full set of variables to substitute at runtime will be the combination of anything defined in `variablesForSubstitution` and all data returned by the `variablesForSubstitutionTask`

Let me know if this works for you and I'll get it merged into the main release!

**Comment by jmcclell** [comment]
Hi @kurtkopchik 

Thank you so much for a quick reply and turnaround!

This is working perfectly for me. I can now use configuration data (such as database port, etc.) defined in my application's config (using Typesafe Config) in the build for Docker and in my docker-compose file.

**Comment by kurtkopchik** [comment]
You are welcome @jmcclell!

The official release with the change is now ready:
`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.14")`
