### ISSUE TITLE
Variable substitution in image tag

### ISSUE THREAD

**Issue by mb720** [Tapad/sbt-docker-compose#41]
Hi Kurt!

I've created a Scala.js sample application using your plugin: https://gitlab.com/bullbytes/scala-js-example
When running the app using `docker-compose up`, I'd like to use an environment variable to define which tag of the image to use (`latest`, `staging`, or `production`).
The default tag should be `latest`.

Thus, I added this to my `docker-compose.yml`, using Docker's [variable substitution with default values](https://docs.docker.com/compose/compose-file/#variable-substitution):

    image: registry.gitlab.com/bullbytes/scala-js-example:${APP_DOCKER_IMAGE_TAG:-latest}

While this works using `docker-compose up`, I run into an error when executing `dockerComposeUp` in SBT:

    Error parsing reference: "registry.gitlab.com/bullbytes/scala-js-example:${APP_DOCKER_IMAGE_TAG:-latest}" is not a valid repository/tag: invalid reference format

Here's my [`docker-compose.yml`](https://gitlab.com/bullbytes/scala-js-example/blob/master/docker-compose.yml).

Thanks!

P.S.: If you have any feedback for my example app (e.g., my [`build.sbt`](https://gitlab.com/bullbytes/scala-js-example/blob/master/build.sbt)), I'd be more than glad to hear it. 😊

**Comment by kurtkopchik** [comment]
Hi @mb720! Very cool project.

So the way that environment variable substitution works with the `sbt-docker-compose` plugin is that you need to define the environment values (or a task that calculates the environment variable values) in your `build.sbt` file. The plug-in then substitutes these values in the compose file before passing it on to docker to process. For reference here is the [PR](https://github.com/Tapad/sbt-docker-compose/pull/17) that added this feature.

There is also an example project [basic-variable-substitution](https://github.com/Tapad/sbt-docker-compose/tree/master/examples/basic-variable-substitution) showing how to use the variable substitution feature.

There are two `build.sbt` settings that can be used to configure environment values in the docker compose file:
`variablesForSubstitution =: // A Map[String,String] of variables to substitute in your docker-compose file. These are substituted substituted by the plugin and not using environment variables.`
`variablesForSubstitutionTask =: // An sbt task that returns a Map[String,String] of variables to substitute in your docker-compose file. These are substituted by the plugin and not using environment variables.`

That being said, looking at your example docker compose file, it looks like Docker introduced a new feature starting in the 2.1 version of the compose file format where you can provide a `-default` value to the environment variable definition:`${VARIABLE:-default}`

The current sbt-docker-compose plugin [code](https://github.com/Tapad/sbt-docker-compose/blob/c77376bd1ca3c22e71a2669c7e2d4384acd2321b/src/main/scala/com/tapad/docker/ComposeFile.scala#L307) does not handle this `-default` value setting at the moment and would have to be updated to support it. For now, you would have to use the standard `${VARIABLE}` format and perform any default value logic in your `build.sbt`. It should be possible to make a code update to the plugin so that it knows how to read the new `-default` value when it exists and use it if nothing was explicitly provided for substitution. I'll have to look into adding this in the future.

I hope this helps!

**Comment by dpfeiffer** [comment]
@kurtkopchik Handling of the variable substitution default value is something I am as well looking forward to.

**Comment by kurtkopchik** [comment]
@dpfeiffer & @mb720 - I made an [update](https://github.com/Tapad/sbt-docker-compose/commit/cb51bae74beb97fe0c2de0295cffde5247d80582) to the plugin that allows it to now handle docker-compose environment variables that are defined using the `${VARIABLE:-default}` format introduced in version 2.1.

If you do not define the environment variable value in the settings `variablesForSubstitution` or `variablesForSubstitutionTask` then the `default` value will be used.

This change has been published in `1.0.22-SNAPSHOT`
```
resolvers += "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.22-SNAPSHOT")
```
Let me know if you find any issues with it before I merge it to master. Apologies for the delay.

**Comment by dpfeiffer** [comment]
@kurtkopchik I will try today

**Comment by kurtkopchik** [comment]
@dpfeiffer - Thank you for verifying! The fix for this issue is now included in an official release:

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.22")`
