### ISSUE TITLE
Docker Compose field 'container_name:' is currently not supported by sbt-docker-compose

### ISSUE THREAD

**Issue by ashishsoni** [Tapad/sbt-docker-compose#46]
What is the reason it is unsupported

**Comment by kurtkopchik** [comment]
Hi @ashishsoni,

When you specify a `container_name` in the compose file you are limited to only having a single instance of it running or an error will be reported as container names need to be [unique per-machine](https://docs.docker.com/compose/compose-file/#containername). 

As a general principle when using docker compose we try to have all of our container instances be dynamically named by Docker itself so that we can have multiple instances running on the same machine whether that be your local box, the build machine or a shared cloud environment like Mesos. So technically support can be added but it will lead to a different issue of an error being reported each time a second 'dockerComposeUp' instance is attempted.

**Comment by ashishsoni** [comment]
Thanks for the information
