### ISSUE TITLE
Error starting Docker Compose instance. Shutting down containers...

### ISSUE THREAD

**Issue by ashishsoni** [Tapad/sbt-docker-compose#47]
I am not sure what is the issue here ...
Created Compose File with Processed Custom Tags: /tmp/compose-updated198967574635630207.yml
Pulling Docker images except for locally built images and images defined as <skipPull> or <localBuild>.
Skipping Pull of image: backendapi:latest
Skipping Pull of image: frontendapi:
Creating network "926046_default" with the default driver
Pulling frontendapi (frontendapi:latest)...
repository frontendapi not found: does not exist or no pull access
No stopped containers
926046_default
Error starting Docker Compose instance. Shutting down containers...

version: '2'
services:
  backendapi:
     image: backendapi:latest<localBuild>
     environment:
         JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
     ports:
      - "5005:5005"
  frontendapi:
       image: frontendapi:<localBuild>
       environment:
           JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
       ports:
        - "5005:5005"

**Comment by kurtkopchik** [comment]
Hi @ashishsoni,

The formatting if the `image` property for the `frontendapi` does not look correct. I would think that you would want to format it as: `image: frontendapi:latest`

The compose instance is failing to start because it cannot find the frontendapi image:
`repository frontendapi not found: does not exist or no pull access`. Does the frontendapi image exist locally or in the docker registry?

This looks like it would also be an issue if you used this docker-compose file directly with Docker outside of the plugin.

**Comment by ashishsoni** [comment]
see below i have execute the compose command directly from the terminal and no issues and also i havent change the file at all.
        
[spark@Mindstorm frontendapi]$ cd docker/
[spark@Mindstorm docker]$ docker-compose up -d
Creating network "docker_default" with the default driver
Creating docker_frontendapi_1
[spark@Mindstorm docker]$ 
When i run the sbt dockerComposeUP it build the images but doesnt start the containers and fails.
 see attached.

[docker-compose.txt](https://github.com/Tapad/sbt-docker-compose/files/858920/docker-compose.txt)

**Comment by kurtkopchik** [comment]
If you can attach the full output from the `dockerComposeUp` command it would be very helpful in getting to the root cause of the issue. 

The `docker-compose.txt` file you attached has the definition for the `backendapi` but the output you showed from running docker-compose directly is from starting the `frontendapi`. Also, any example build.sbt config you can provide showing how the plugin is configured would be help. Trying it myself I was able to correctly start up an instance of the docker-compose.txt file using the plugin.

**Comment by ashishsoni** [comment]
Hi Do you have a bitbucket user name or email id i can provide you access of the repo and you can reproduce

**Comment by ashishsoni** [comment]
I have attached the whole project , Please try 
[justbuyapi.tar.gz](https://github.com/Tapad/sbt-docker-compose/files/859463/justbuyapi.tar.gz)

**Comment by kurtkopchik** [comment]
Hi @ashishsoni,

I believe that the issue is since you are running only from the sub-projects and not from the root you need to also define the `dockerImageCreationTask` setting in the sub-projects.

There should have been a warning message printed to the output indicating this:
`***Warning: The 'dockerImageCreationTask' has not been defined. Please configure this setting to have Docker images built.***`

When I add the setting `dockerImageCreationTask := docker.value` to the `frontendapi` and `backendapi` sub-projects directly I am able to start them successfully with `dockerComposeUp`.
```
lazy val frontendapi = project.from("frontendapi")
  .setName("frontendapi")
  .setDescription("front end")
  .setInitialCommand("_")
  .configureModule
  .dependsOnProjects(common)
  .enablePlugins(sbtdocker.DockerPlugin, DockerComposePlugin)
  .settings(assmSettings)
  .settings(
    dockerImageCreationTask := docker.value,
    dockerfile in docker := {
      new Dockerfile {
        val mainClassString = (mainClass in Compile).value.get
        val classpath = (fullClasspath in Compile).value
        from("java")
        add(classpath.files, dockerAppPath)
        entryPoint("java", "-cp", s"$dockerAppPath:$dockerAppPath/*", s"$mainClassString")
      }
    },
    imageNames in docker := Seq(ImageName(
      repository = name.value.toLowerCase,
      tag = Some("latest"))
    )
  )

```

Hopefully that will do the trick for you as well. Let me know.

**Comment by ashishsoni** [comment]
Thanks for continue help but i am seeing the same error .
I have attached the completed console.log as well as the project again after the modification you mentioned.
Also below is the my environment
Centos 7 
Docker Version 

[spark@Mindstorm justbuyapi]$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: false

Docker Compose Version

[spark@Mindstorm justbuyapi]$ docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.5
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013

[justbuyapi.tar.gz](https://github.com/Tapad/sbt-docker-compose/files/859860/justbuyapi.tar.gz)

[console.txt](https://github.com/Tapad/sbt-docker-compose/files/859861/console.txt)

**Comment by kurtkopchik** [comment]
Hi @ashishsoni,

I thought that you were only interested in running `dockerComposeUp` from the sub-projects and not from the `root` so I didn't try it from the `root` project in the example you provided. When I do run it from the `root` I noticed that you have a mistake in your `docker-compose.yml` file.

`image: frontendapi:<localBuild>`

Needs to be defined as:
`image: frontendapi:latest<localBuild>`

Your `image` definition for `backendapi` was done correctly.

After making that change it worked correctly for me. Hopefully that does the trick for you as well! Let me know how it goes.

**Comment by ashishsoni** [comment]
Totally My bad .
Thank you very much really appreciated your help. It is working now

**Comment by kurtkopchik** [comment]
Happy to hear that it's working now!
