### ISSUE TITLE
More information about containers for tests

### ISSUE THREAD

**Issue by sauliusvl** [Tapad/sbt-docker-compose#7]
Hi,

I would like to write tests that involve stopping/killing/relaunching containers -- I could do that by simply invoking docker as a shell command, however currently there's no reliable way to figure out which container I should interact with.

I wanted to submit a PR that passes the full information about the running services to the test runner e.g. [like this](https://github.com/sauliusvl/sbt-docker-compose/commit/c355d03eb0cd457d17f092f8bf7e2759cd8336b5), but couldn't decide on the exact syntax, i.e. should it be something like `zookeeper:id=abc123 zookeeper:tag=3.4.8` or something else.

Any suggestions / existing plans regarding this ?

**Comment by kurtkopchik** [comment]
Hi,

Thanks for looking to contribute to the plugin! Passing additional information on the running instance to the test cases is a great area to enhance and something that I wanted to get done as well.

The current format for getting the running host and port info is:
"<servicename>:<containerPort>=<host>:<hostPort>"

In order to not break compatibility and allow more properties to be added in the future I'm thinking something like this: 
"<servicename>:containerId=<containerId>"
So the test case code to look up the container id for a service would be:
"myservice:containerId" and it would return 54803f8a6938 for example.

So similar to what you have but adding the "containerId" string qualifier so that additional properties could be added and it's clear what you expect to be returned.

**Comment by kurtkopchik** [comment]
Version 1.0.6 is now published with your changes. Thanks again!

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.6")`
