### ISSUE TITLE
Are there any special issues with Akka (Akka HTTP)?

### ISSUE THREAD

**Issue by favetelinguis** [Tapad/sbt-docker-compose#76]
First of I would like to thank you very much for an excellent contribution to the Scala ecosystem. I have been spending the whole weekend Googling how to get a proper integration test environment setup in Scala for my simple hobby project and to my big surprise it turns out there are not any very good alternatives until i found this project. It does exactly what I want, enable me to run proper integration tests to a stand alone instance.

However, I manage to get most things setup but Im still not able to access my Akka HTTP server on OSX.

This is the output that `dockerComposeUp` gives me:
```
+---------+-----------------+--------------+--------------+----------------+--------------+---------+
| Service | Host:Port       | Tag Version  | Image Source | Container Port | Container Id | IsDebug |
+=========+=================+==============+==============+================+==============+=========+
| bfg     | localhost:32770 | 0.1.SNAPSHOT | build        | 8080           | 4e1c0460bcf0 |         |
| bfg     | localhost:32771 | 0.1.SNAPSHOT | build        | 5005           | 4e1c0460bcf0 | DEBUG   |
+---------+-----------------+--------------+--------------+----------------+--------------+---------+
```

Running

>  docker-compose -p 206507 -f /var/folders/yh/mm1bdmx9073_b15lw69b2qmh0000gn/T/compose-updated6736504145219745864.yml logs -f

Gives me the last line wich looks ok:

`bfg_1  | 17:04:47 [default-akka.actor.default-dispatcher-3] INFO  com.bfg.infrastructure.server.Server - Server started on /127.0.0.1:8080`

However when Im not running with docker-compose I can access my server with:
`localhost:8080`

However trying:
`localhost:32770`
Which should be the same when Im using docker-compose just gives me this i Chrome:

> This page isn’t working
> 
> localhost didn’t send any data.
> ERR_EMPTY_RESPONSE

This is the content of `build.sbt` wich is a mix from your multi-project example and the integration test example.
```
import Dependencies._
import java.io.File

lazy val commonSettings = Seq(
  version := "0.1.SNAPSHOT",
  organization := "com.bfg",
  scalaVersion := "2.12.1"
)
enablePlugins(DockerComposePlugin)

docker <<= (docker in bfg) map {(image) => image}

//Set the image creation Task to be the one used by sbt-docker
dockerImageCreationTask := docker.value


lazy val bfg = project
  .settings(
    name := "bfg",
    Defaults.itSettings,
    commonSettings,
    libraryDependencies ++= commonDeps,
    libraryDependencies += "org.scalaj" %% "scalaj-http" % "2.3.0" % "it",
      //To use 'dockerComposeTest' to run tests in the 'IntegrationTest' scope instead of the default 'Test' scope:
      // 1) Package the tests that exist in the IntegrationTest scope
      testCasesPackageTask := (sbt.Keys.packageBin in IntegrationTest).value,
      // 2) Specify the path to the IntegrationTest jar produced in Step 1
      testCasesJar := artifactPath.in(IntegrationTest, packageBin).value.getAbsolutePath,
      // 3) Include any IntegrationTest scoped resources on the classpath if they are used in the tests
      testDependenciesClasspath := {
        val fullClasspathCompile = (fullClasspath in Compile).value
        val classpathTestManaged = (managedClasspath in IntegrationTest).value
        val classpathTestUnmanaged = (unmanagedClasspath in IntegrationTest).value
        val testResources = (resources in IntegrationTest).value
        (fullClasspathCompile.files ++ classpathTestManaged.files ++ classpathTestUnmanaged.files ++ testResources).map(_.getAbsoluteFile).mkString(File.pathSeparator)
      },

      dockerfile in docker := {
          new Dockerfile {
          val dockerAppPath = "/app/"
          val mainClassString = (mainClass in Compile).value.get
          val classpath = (fullClasspath in Compile).value
          from("java")
          add(classpath.files, dockerAppPath)
          entryPoint("java", "-cp", s"$dockerAppPath:$dockerAppPath/*", s"$mainClassString")
        }
      },

      imageNames in docker := Seq(ImageName(
        repository = name.value.toLowerCase,
        tag = Some(version.value))
      )
    )
    .configs(IntegrationTest)
    .enablePlugins(DockerPlugin, DockerComposePlugin)
```

And the docker-compose.yml
```
bfg:
  image: bfg:0.1.SNAPSHOT
  environment:
    JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
  ports:
    - "0:8080"
    - "0:5005"
```

My questions is if there are any know additional steps need to get Akka Http working or if you could give any hints on how to debug the issue more? Any input would be appreciated since I would really like to get this working.

**Comment by kurtkopchik** [comment]
Hi @favetelinguis, thanks for using the plugin!

At the moment I'm not aware of any special steps that need to be taken to get Akka Http projects working. As far as I know it should work just like any other docker / docker-compose project.

A few ideas would be to run `docker ps `in another command shell after you run `dockerComposeUp` and validate the container _is indeed still up and running_ and that the port mappings match what is in the output table from `dockerComposeUp`. If the container on port 8080 started and the quickly exited I could see it exhibiting the behavior you are describing.

```
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                              NAMES
c04b0055c523        basic:1.0.0         "java -cp /app/:/a..."   5 minutes ago       Up 5 minutes        0.0.0.0:32770->5005/tcp, 0.0.0.0:32768->8080/tcp   724305_basic_1
```

You should then be able to execute `curl localhost:32768` <whatever the dynamic port for 8080 is> to test out that you can connect to the endpoint and get the expected result.

If that all looks correct and it's still not working. Since your `docker-compose.yml` file is pretty simple you can go into the directory where it exists and run `docker-compose up` which will start a compose instance independent of the plugin. You can then run `docker-compose ps` in the same directory of the compose yml file to get the port information to connect to. This will help determine if it's an issue related to the plugin or something with the docker-compose / image you are using.

Let me know what you find. Hopefully we can get you up and running soon!

**Comment by favetelinguis** [comment]
I have tried your tips but still the same result. And when im debugging my controllers are never executed (i was however able to connect to the debug port). I have put together a minimal example of akka http with docker compose.

**Comment by kurtkopchik** [comment]
Hi @favetelinguis - Thanks for making the sample project. It made it much easier to troubleshoot the issue. From looking around on the web it appears that there are some issues with using `localhost` in a Docker container on externally exposed ports. The fix is to use `0.0.0.0` as the bind address instead.

Here is a PR with the changes that work when I tested it:
https://github.com/favetelinguis/akka-http-docker-compose/pull/1

I changed the route to be `test` as well. Let me know if this gets you up and running.

(Thanks to @tobym for his assistance as well!)

**Comment by favetelinguis** [comment]
Yes this fixed it! Nice thank you very much. The only issue I have now is where to place the yml file. If I place it outside the project folder in a separate docker file under the main project the plugin cant find it. In the documentation and other sample it says this is a valid place to put it?

**Comment by favetelinguis** [comment]
Thanks for all the help!

**Comment by kurtkopchik** [comment]
Hi @favetelinguis - I'm happy to hear it's working now!

The plugin settings are on a per-project basis. By default the plugin will [look](https://github.com/Tapad/sbt-docker-compose/blob/master/src/main/scala/com/tapad/docker/DockerComposeSettings.scala#L14) for the compose file in the resources folder of the project followed by a docker folder off the base directory of the project followed by the `root` directory. 

To enable the plugin to work from within the `bfg` sub-project you can either move the `docker` folder with the `docker-compose.yml` file to be under that project or you can use the `composeFile` setting to have the `bfg` project use the docker file from the `root` project. 

Here is a PR on your test project showing the changes:
https://github.com/favetelinguis/akka-http-docker-compose/pull/2
