### ISSUE TITLE
Specs2 support

### ISSUE THREAD

**Issue by missingfaktor** [Tapad/sbt-docker-compose#86]
In addition to ScalaTest, it would be cool to have support for Specs2. If there is interest and if you could guide me on how I can go about this, I could find some time and try to do this myself.

**Comment by kurtkopchik** [comment]
Hi @missingfaktor,

I put together some prototype code in the [feature/specs2 ](https://github.com/Tapad/sbt-docker-compose/compare/feature/specs2) branch for how you could execute `Specs2` tests using the `sbt-docker-compose` plugin.

Basically in your `build.sbt` file you can now configure the following setting to specify that you would like to use `Specs2` instead of the default `ScalaTest`:
`testPassUseSpecs2 := true`

Currently when the `Specs2` test pass is run it attempts to run all of the test cases under `src/test/scala` using the `specs2.runner.files` option. I haven't tried to modify any of the potential parameters that can be passed to `Specs2` to change the default behavior. For example, to only run a subset of tests. However, you can potentially use the existing `testExecutionExtraConfigTask` plugin setting to do so.

Checkout the [basic-with-tests-specs2](https://github.com/Tapad/sbt-docker-compose/tree/feature/specs2/examples/basic-with-tests-specs2) example for a `Specs2` test case that is executed via `dockerComposeTest`. Since `Specs2` does not have a `configMap` like `ScalaTest` the Docker port and container information is shared with the tests using `System Properties`.

Take a look and let me know what you think. Feel free to make additional changes to help support what you need in terms of `Specs2` functionality. Thanks for using the plugin!

**Comment by missingfaktor** [comment]
Hello, @kurtkopchik. Thanks for the prompt response! The existing support seems complete. Are you planning to make a non-snapshot release soon?

**Comment by kurtkopchik** [comment]
Hi @missingfaktor -  I hope to get this in an official release shortly. I still need to update the documentation before doing so.

**Comment by kurtkopchik** [comment]
Hi @missingfaktor - I've put out an official release that has initial support for Specs2:

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.26")`

Thanks again for the feedback!

**Comment by missingfaktor** [comment]
Thanks a lot, mate!
