### ISSUE TITLE
Executing specific tags runs all tests

### ISSUE THREAD

**Issue by shashidesai** [Tapad/sbt-docker-compose#93]
Thanks for the nice plugin !

I have question about tagging tests:

* I am trying to use the basic example - https://github.com/Tapad/sbt-docker-compose/blob/master/examples/basic-with-tests/build.sbt

* Modified this line - https://github.com/Tapad/sbt-docker-compose/blob/master/examples/basic-with-tests/build.sbt#L15  --> Changed it to this  
`testTagsToExecute := "DockerComposeTag,UnitTestTag"`

* Modified the tests and added tags - Used the basic test - `https://github.com/Tapad/sbt-docker-compose/blob/master/examples/basic-with-tests/src/test/scala/BasicAppSpec.scala`
https://gist.github.com/shashidesai/a5728efd1088ca5a31f9663c0b0296ce

* When I run `sbt dockerComposeTest -tags:DockerComposeTag` or `sbt dockerComposeTest -tags:UnitTestTag`
All the tests are run. 

As per the documentation I thought tagging different tests and using `-tags` should run only those specific tests and not all. Is my understanding wrong ?

**Comment by kurtkopchik** [comment]
Hi @shashidesai,

I believe what is going on is that the examples in the `README` are showing the usage of the commands once you are in `sbt`. Since you are calling the commands from outside of `sbt` you'll need to quote the input for it to work properly. 

For example:
`sbt dockerComposeTest -tags:DockerComposeTag`
should be:
`sbt 'dockerComposeTest -tags:DockerComposeTag'`

I'll update the README to specify this as well. Let me know if doing this works for you and thanks for using the plugin!

**Comment by shashidesai** [comment]
cool. Made that change and that works ! 
Thanks for the quick response :)
