### ISSUE TITLE
Feature request: Support container_name and build, context

### ISSUE THREAD

**Issue by shashidesai** [Tapad/sbt-docker-compose#95]
Currently we see a warning in red saying that container_name and build are not supported. 
Was wondering if you plans to add those two features ?
Excuse me for posting it as an issue, there wasn't a https://gitter.im channel in the repo, so posted here to know if there are any plans to do these features in the near future ?

**Comment by kurtkopchik** [comment]
Hi @shashidesai,

`container_name` is not supported because we want to allow for the launching of multiple `docker-compose` instances. See issue https://github.com/Tapad/sbt-docker-compose/issues/46 for more details.

The plugin is designed to have the image building performed by either `sbt-docker` or` sbt-native-packager`. There are no near to term plans to add support for the `docker-compose` build option.

The list of unsupported docker-compose fields is located in the [README](https://github.com/Tapad/sbt-docker-compose#currently-unsupported-docker-compose-fields).

**Comment by shashidesai** [comment]
Noted. Thanks @kurtkopchik
