### ISSUE TITLE
SBT 1.1.0-M1 compatibility issues

### ISSUE THREAD

**Issue by andrezimmermann** [Tapad/sbt-docker-compose#99]
I tried out the SBT 1.1.0-M1 and they are enforcing that all `AttributteKey(key:string,description:String)`'s key need to start with a lowercase letter.

There is a offending attribute declaration at https://github.com/Tapad/sbt-docker-compose/blob/8a8fa066da94cbf686164a72387deab5fcfd7be5/src/main/scala/com/tapad/docker/DockerComposeKeys.scala#L28
Could you take a look at this?

**Comment by kurtkopchik** [comment]
Hi @andrezimmermann - Thanks for reporting this compatibility issue with `SBT 1.1.0-M1`. 

I believe that I have fixed the root cause and have released a `1.0.30-SNAPSHOT` version with the update. Please try it out and let me know if it works for you so that I can get the changes into the master branch and included in the next official release.

```
resolvers += "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.30-SNAPSHOT")
```

**Comment by andrezimmermann** [comment]
Sorry for the late reply, is working fine with the SNAPSHOP, thanks!

**Comment by kurtkopchik** [comment]
Hi @andrezimmermann - I've included the fix in an official release:

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.30")`

Thanks again for using the plugin and reporting this issue!
